Finalising first release [4]

diff --git a/system/bin/tsbinds b/system/bin/tsbinds
--- a/system/bin/tsbinds
+++ b/system/bin/tsbinds
@@ -1,4 +1,13 @@
 #!/system/xbin/bash
+if ! ls /data > /dev/null 2> /dev/null; then
+    echo "[!] ERROR"
+    echo "    ts-binds needs to be invoked"
+    echo "    from an elevated shell."
+    echo "    Please run 'su' first."
+    echo ""
+    echo "Terminating.."
+    exit 1
+fi
 MODDIR=/magisk/ts-binds
 int=/data/media/0
 sd=/mnt/media_rw/
@@ -18,7 +27,7 @@ else
 fi
 sd=$sd$sdname
 function printhelp {
-    echo "tsbinds [options][arg]"
+    echo "tsbinds [options] [arg]"
     echo ""
     echo "Available options:"
     echo ""
@@ -27,7 +36,7 @@ function printhelp {
     echo "bind all            Binds all entries "
     echo "unbind <bind name>  Unbinds a specific"
     echo "                    entry by its name"
-    echo "unbind all          Uninds all entries"
+    echo "unbind all          Unbinds all entries"
     echo "update              Update cached entries if"
     echo "                    the user's entries are"
     echo "                    modified"
@@ -77,12 +86,14 @@ elif [ $1 == "bind" ]; then
         tslog "All entries were processed"
     elif ! grep -q $2 $folderlist; then
         tslog "Unable to bind $2, entry not found in list!"
+    elif grep -q $2 /proc/mounts; then
+        tslog "$2 is already binded"
     else
         function folderbind {
             mount -o bind "$sd$2" "$int$3" && tslog "Bind successful: $sd$2" || tslog "Bind failed: $sd$2"
         }
         tslog "Binding $2"
-        eval $(grep -q $2 $folderlist)
+        eval $(grep $2 $folderlist)
         tslog "Process completed"
     fi
 elif [ $1 == "unbind" ]; then
@@ -114,16 +125,31 @@ elif [ $1 == "unbind" ]; then
         tslog "All entries were processed"
     elif ! grep -q $2 $folderlist; then
         tslog "Unable to bind $2, entry not found in list!"
+    elif ! grep -q $2 /proc/mounts; then
+        tslog "$2 is already unbinded"
     else
         function folderbind {
             umount "$int$3" && tslog "Unmount successful: $sd$2" || tslog "Unmount failed: $sd$2"
         }
         tslog "Unbinding $2"
-        eval $(grep -q $2 $folderlist)
+        eval $(grep $2 $folderlist)
         tslog "Process completed"
     fi
+elif [ $1 == "check" ]; then
+    if [ ! $2 ]; then
+        echo 'E: Bind name is not provided!';
+    elif ! grep -q $2 $folderlist; then
+        tslog "Unable to check $2, entry not found in list!"
+    elif grep -q $2 /proc/mounts; then
+        tslog "$2 is binded"
+    else
+        tslog "$2 is NOT binded"
+    fi
 elif [ $1 == "update" ]; then
-    if [ ! $folderlist -nt $folderlistuser ]; then
+    if [ $2 == "f" ]; then
+        cp $folderlistuser $folderlist
+        tslog "Force-updated cached list"
+    elif [ ! $folderlist -nt $folderlistuser ]; then
         tslog "Difference found between cached and original user list"
         cp $folderlistuser $folderlist
         chmod 0755 $folderlist
