Cleanup more

diff --git a/system/bin/tsbinds b/system/bin/tsbinds
--- a/system/bin/tsbinds
+++ b/system/bin/tsbinds
@@ -24,6 +24,8 @@ else
            break
        fi
     done
+    chmod 0755 $sdnamecache
+    chown 0:0 $sdnamecache
 fi
 sd=$sd$sdname
 function printhelp {
@@ -57,23 +59,21 @@ function printhelp {
     echo "reinit ............ Re-run the script that"
     echo "                    runs on boot"
     echo ""
-    echo "Note: running a command with \"all\" argument may return"
-    echo "      \"unmount\" errors for some functions. Most of the"
-    echo "      time they can be safely ignored."
+    echo "Note: running the command reinit, and unbind, move with \"all\" argument may return \"unmount\" errors for some functions. Most of the time they can be safely ignored."
 }
 function tslog {
     echo -e "$(date +'%F %T'):\n  $1\n" >> $logfile
     echo -e "$1"
 }
-if [ ! $1 ]; then
+if [ ! "$1" ]; then
     echo "E: No action is declared!"
     echo ''
     printhelp
-elif [ $1 == "help" ] || [ $1 == "h" ]; then
+elif [ "$1" == "help" ] || [ "$1" == "h" ]; then
     printhelp
-elif [ $1 == "bind" ]; then
+elif [ "$1" == "bind" ]; then
     function folderbind {
-        if grep -q $int$3 /proc/mounts; then
+        if grep -q "$int$3" /proc/mounts; then
             tslog "$1 is already binded"
         elif [ ! -d "$sd$2" ]; then
             tslog "Bind aborted: Folder '$sd$2' on SD CARD doesn't exist!"
@@ -85,52 +85,52 @@ elif [ $1 == "bind" ]; then
             mount -o bind "$sd$2" "$int$3" && tslog "Bind successful: $1" || tslog "Bind failed: $1"
         fi
     }
-    if [ ! $2 ]; then
+    if [ ! "$2" ]; then
         echo 'E: Bind name is not provided!';
-    elif [ $2 == "all" ]; then
+    elif [ "$2" == "all" ]; then
         tslog "Binding all entries"
         source $folderlist
         tslog "All entries were processed"
-    elif line=$(grep $2 $folderlist); then
+    elif line="$(grep "$2" $folderlist)"; then
         eval $line
     else
         tslog "Unable to bind $2, entry not found in list!"
     fi
-elif [ $1 == "unbind" ]; then
+elif [ "$1" == "unbind" ]; then
     function folderbind {
-        if grep -q $int$3 /proc/mounts; then
+        if ! grep -q "$int$3" /proc/mounts; then
             tslog "$1 is already unbinded"
         else
             umount "$int$3" && tslog "Unbind successful: $1" || tslog "Unbind failed: $1"
         fi
     }
-    if [ ! $2 ]; then
+    if [ ! "$2" ]; then
         echo 'E: Bind name is not provided!';
-    elif [ $2 == "all" ]; then
+    elif [ "$2" == "all" ]; then
         tslog "Unbinding all entries"
         source $folderlist
         tslog "All entries were processed"
-    elif line=$(grep $2 $folderlist); then
+    elif line="$(grep "$2" $folderlist)"; then
         eval $line
     else
         tslog "Unable to unbind $2, entry not found in list!"
     fi
-elif [ $1 == "check" ]; then
+elif [ "$1" == "check" ]; then
     function folderbind {
-        grep -q $int$3 /proc/mounts && tslog "$1 is BINDED" || tslog "$1 is NOT binded"
+        grep -q "$int$3" /proc/mounts && tslog "$1 is BINDED" || tslog "$1 is NOT binded"
     }
-    if [ ! $2 ]; then
+    if [ ! "$2" ]; then
         echo 'E: Bind name is not provided!';
-    elif [ $2 == "all" ]; then
+    elif [ "$2" == "all" ]; then
         source $folderlist
         tslog "All entries were checked"
-    elif line=$(grep $2 $folderlist); then
+    elif line="$(grep "$2" $folderlist)"; then
         eval $line
     else
         tslog "Unable to check $2, entry not found in list!"
     fi
-elif [ $1 == "update" ]; then
-    if [ $2 == "f" ]; then
+elif [ "$1" == "update" ]; then
+    if [ "$2" ] && [ "$2" == "f" ]; then
         cp -f $folderlistuser $folderlist
         tslog "Force-updated cached list"
     elif [ ! $folderlist -nt $folderlistuser ]; then
@@ -142,10 +142,10 @@ elif [ $1 == "update" ]; then
     else
         tslog "No update made to cached list"
     fi
-elif [ $1 == "move" ]; then
-    if [ ! $2 ]; then
+elif [ "$1" == "move" ]; then
+    if [ ! "$2" ]; then
         echo 'E: Bind name is not provided!'
-    elif [ $2 == "all" ]; then
+    elif [ "$2" == "all" ]; then
         tsbinds unbind all
         function folderbind {
             if [ "$(ls -A "$int$3")" ]; then
@@ -156,8 +156,9 @@ elif [ $1 == "move" ]; then
         }
         source $folderlist
         tsbinds bind all
-    elif line=$(grep $2 $folderlist); then
+    elif line="$(grep "$2" $folderlist)"; then
         function folderbind {
+            wasBinded=no
             if grep -q "$int$3" /proc/mounts; then
                 wasBinded=yes
                 tsbinds unbind $1
@@ -175,7 +176,7 @@ elif [ $1 == "move" ]; then
     else
         tslog "Unable to move contents of $2, entry not found in list!"
     fi
-elif [ $1 == "reinit" ]; then
+elif [ "$1" == "reinit" ]; then
     tsbinds unbind all
     $MODDIR/service.sh
 else
