Now script no longer output to log
This is because tsbinds is a script that acts as an application in the
terminal. It is expected for it to work like other terminal apps, which
is, to only output to stdout unless piped.

diff --git a/system/xbin/tsbinds b/system/xbin/tsbinds
--- a/system/xbin/tsbinds
+++ b/system/xbin/tsbinds
@@ -42,11 +42,6 @@ function supass {
     /sbin/su -M -c "$@"
 }
 
-function gexit {
-    echo "Error occured here. Exiting" | $log
-    exit 1
-}
-
 function printhelp {
     echo "tsbinds [options] [arg]"
     echo
@@ -107,106 +102,106 @@ elif [ "$1" == "help" ] || [ "$1" == "h" ]; then
 elif [ "$1" == "bind" ]; then
     function folderbind {
         if supass mountpoint -q \""$3"\"; then
-            echo "$1 is already binded" | $log
+            echo "$1 is already binded"
         elif [ ! -d "$2" ] && [ ! -f "$2" ]; then
-            echo "Bind aborted: Folder '$2' as source doesn't exist!" | $log
+            echo "Bind aborted: Folder '$2' as source doesn't exist!"
             exit 1
         elif [ ! -d "$3" ] && [ ! -f "$3" ]; then
-            echo "Bind aborted: Folder '$3' as target doesn't exist!" | $log
+            echo "Bind aborted: Folder '$3' as target doesn't exist!"
             exit 1
         else
-            echo "Binding $1" | $log
-            if supass mount --rbind \""$2"\" \""$3"\" 2>> $logfile; then
+            echo "Binding $1"
+            if supass mount --rbind \""$2"\" \""$3"\"; then
                 if [ $legacy != "1" ]; then
                     intr="$(echo $3 | sed 's/default/read/g')"
                     intw="$(echo $3 | sed 's/default/write/g')"
-                    (supass mount -o remount,gid=9997,mask=6 \""$intr"\") || gexit
-                    (supass mount -o remount,gid=9997,mask=6 \""$intw"\") || gexit
+                    (supass mount -o remount,gid=9997,mask=6 \""$intr"\") || exit 1
+                    (supass mount -o remount,gid=9997,mask=6 \""$intw"\") || exit 1
                 fi
-                echo "Bind successful" | $log
+                echo "Bind successful"
             else
-                echo "Bind failed" | $log
+                echo "Bind failed"
             fi
         fi
     }
     if [ ! "$2" ]; then
-        echo 'E: Bind name is not provided!' | $log
+        echo 'E: Bind name is not provided!'
     elif [ "$2" == "all" ]; then
-        echo "Binding all entries" | $log
+        echo "Binding all entries"
         source $folderlist
-        echo "All entries were processed" | $log
+        echo "All entries were processed"
     elif [ "$2" == "o" ]; then
         folderbind "o" "$3" "$4"
     elif line="$(grep -m 1 "$2" $folderlist)"; then
         eval $line
     else
-        echo "Unable to bind $2, entry not found in list!" | $log
+        echo "Unable to bind $2, entry not found in list!"
     fi
 
 # Unbind -------------------------------------------------
 elif [ "$1" == "unbind" ]; then
     function folderbind {
         if ! supass mountpoint -q \""$3"\"; then
-            echo "$1 is already unbinded" | $log
+            echo "$1 is already unbinded"
         else
-            echo "Unbinding $1" | $log
-            if supass umount \""$3"\" 2>> $logfile
-                then echo "Unbind successful: $1" | $log
-                else echo "Unbind failed: $1" | $log;
+            echo "Unbinding $1"
+            if supass umount \""$3"\"
+                then echo "Unbind successful: $1"
+                else echo "Unbind failed: $1";
             fi
         fi
     }
     if [ ! "$2" ]; then
-        echo 'E: Bind name is not provided!' | $log
+        echo 'E: Bind name is not provided!'
     elif [ "$2" == "all" ]; then
-        echo "Unbinding all entries" | $log
+        echo "Unbinding all entries"
         source $folderlist
-        echo "All entries were processed" | $log
+        echo "All entries were processed"
     elif [ "$2" == "o" ]; then
         folderbind "o" "$3" "$4"
     elif line="$(grep -m 1 "$2" $folderlist)"; then
         eval $line
     else
-        echo "Unable to unbind $2, entry not found in list!" | $log
+        echo "Unable to unbind $2, entry not found in list!"
     fi
 
 # Check --------------------------------------------------
 elif [ "$1" == "check" ]; then
     function folderbind {
         if supass mountpoint -q \""$3"\"
-            then echo "$1 is BINDED" | $log
-            else echo "$1 is NOT binded" | $log
+            then echo "$1 is BINDED"
+            else echo "$1 is NOT binded"
         fi
     }
     if [ ! "$2" ]; then
-        echo 'E: Bind name is not provided!' | $log
+        echo 'E: Bind name is not provided!'
     elif [ "$2" == "all" ]; then
         source $folderlist
-        echo "All entries were checked" | $log
+        echo "All entries were checked"
     elif line="$(grep -m 1 "$2" $folderlist)"; then
         eval $line
     else
-        echo "Unable to check $2, entry not found in list!" | $log
+        echo "Unable to check $2, entry not found in list!"
     fi
 
 # Update -------------------------------------------------
 elif [ "$1" == "update" ]; then
     if [ ! -f $folderlistuser ]; then
-        cp $datadir/fresh-folderlist.txt $folderlistuser  2>> $logfile
-        echo "Copied user list to internal storage" | $log
+        cp $datadir/fresh-folderlist.txt $folderlistuser
+        echo "Copied user list to internal storage"
         tsbinds update
     elif [ ! -f $folderlist ]; then
-        cp $folderlistuser $folderlist 2>> $logfile
-        echo "Cached the user list" | $log
+        cp $folderlistuser $folderlist
+        echo "Cached the user list"
     elif [ "$2" ] && [ "$2" == "f" ]; then
-        cp -f $folderlistuser $folderlist 2>> $logfile
-        echo "Force-updated cached list" | $log
+        cp -f $folderlistuser $folderlist
+        echo "Force-updated cached list"
     elif [ ! $folderlist -nt $folderlistuser ]; then
-        echo "Difference found between cached and original user list" | $log
-        cp -f $folderlistuser $folderlist 2>> $logfile
-        echo "Updated cached list" | $log
+        echo "Difference found between cached and original user list"
+        cp -f $folderlistuser $folderlist
+        echo "Updated cached list"
     else
-        echo "No update made to cached list" | $log
+        echo "No update made to cached list"
     fi
 
 # Reinit -------------------------------------------------
@@ -218,16 +213,16 @@ elif [ "$1" == "reinit" ]; then
 elif [ "$1" == "disable" ]; then
     if [ ! -f $datadir/disable ]; then
         touch $datadir/disable
-        echo "ts-binds automatic bind disabled" | $log
+        echo "ts-binds automatic bind disabled"
     else
-        echo "Already disabled!" | $log
+        echo "Already disabled!"
     fi
 elif [ "$1" == "enable" ]; then
     if [ ! -f $datadir/disable ]; then
-        echo "Already enabled!" | $log
+        echo "Already enabled!"
     else
-        rm -f $datadir/disable 2>> $logfile
-        echo "ts-binds automatic bind enabled" | $log
+        rm -f $datadir/disable
+        echo "ts-binds automatic bind enabled"
     fi
 
 # Print log ----------------------------------------------
@@ -256,28 +251,28 @@ elif [ "$1" == "legacy" ]; then
         echo "tsbinds legacy off     :: to force off (SDCardFS)"
         echo "tsbinds legacy default :: to fallback to default"
     elif [ "$2" == "off" ]; then
-        echo "Forcing SDCardFS" | $log
+        echo "Forcing SDCardFS"
         if [ -f $datadir/legacy ]; then rm -f $datadir/legacy; fi
         echo "resetprop -p ro.sys.sdcardfs true" > $MODDIR/post-fs-data.sh
         echo "resetprop -p persist.sys.sdcardfs force_on" >> $MODDIR/post-fs-data.sh
         echo "resetprop -p persist.fuse_sdcard false" >> $MODDIR/post-fs-data.sh
     elif [ "$2" == "on" ]; then
-        echo "Forcing FUSE" | $log
+        echo "Forcing FUSE"
         if [ ! -f $datadir/legacy ]; then touch $datadir/legacy; fi
         echo "resetprop -p ro.sys.sdcardfs false" > $MODDIR/post-fs-data.sh
         echo "resetprop -p persist.sys.sdcardfs force_off" >> $MODDIR/post-fs-data.sh
         echo "resetprop -p persist.fuse_sdcard true" >> $MODDIR/post-fs-data.sh
     elif [ "$2" == "default" ]; then
-        echo "Setting Default" | $log
+        echo "Setting Default"
         if [ -f $datadir/legacy-device ] && [ ! -f $datadir/legacy ]; then touch $datadir/legacy; fi
         if [ -f $MODDIR/post-fs-data.sh ]; then rm -f $MODDIR/post-fs-data.sh; fi
     else
-        echo "Unknown parameter: ${2}!" | $log
+        echo "Unknown parameter: ${2}!"
     fi
 
 # Action unrecognised ------------------------------------
 else
-    echo "E: Unknown action \"$1\" supplied" | $log
+    echo "E: Unknown action \"$1\" supplied"
 fi
 
 # Force log proper permission ----------------------------
